#database settings
spring:
  data:
    redis:
      timeout: 600ms
      host: localhost
      port: 6379
# togglz settings
togglz:
  enabled: true
  console:
    enabled: true
    path: /togglz-console
    secured: true
  max-connection-pool: 10
  max-idle-connection: 5
  min-idle-connection: 1
  max-wait: 3000
  username: admin
  feature-admin: true